config/routes.rb
Rails.application.routes.draw do

  resources :hotels do
    resources :bookings
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",:registrations => "registrations",:sessions => "sessions"}

  resources :users do
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :hotels
      resources :bookings
    end
  end

  resources :bookings
  root 'welcome#index'

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :hotel
  belongs_to :user
  attr_reader :status

  def estado
    if status?
      return "Activa"
    else
      return "Cancelada"
    end
  end


end

app/controllers/api/v1/bookings_controller.rb
module Api
  module V1
    class BookingsController < ApplicationController
      #TODO falta hacer que reconozca el hotel_id como atributo
      before_action :set_booking, only: [:show, :edit, :update, :destroy]
      # before_action :set_hotel, only: [:new,:create]
      acts_as_token_authentication_handler_for User
      respond_to :json

      def index
        # respond_with Booking.where(user_id: params[:user_id])
        @bookings = current_user.bookings
        render :json => {bookings: @bookings}
      end

      def show
            render json: @booking
      end

      def create
        @booking = current_user.bookings.new(booking_params)
        @booking.hotel = @hotel
        respond_to do |format|
          if @booking.save
            format.json { render json: @booking }
          else
            format.json { render json: @booking.errors, status: :unprocessable_entity }
          end
        end
      end

      def update
        respond_to do |format|
          if @booking.update(booking_params)
            format.json { head :no_content }
          else
            format.json { render json: @booking.errors, status: :unprocessable_entity }
          end
        end
      end

      def destroy
        #TODO hacer que borre solo los que pertenecen a ese usuario
        if @booking.destroy
          render json: {:code => 0}
        else
          render json: {:code => 1, :messages => @booking.errors.full_messages}
        end

      end

      def edit
        super
      end

      private

      # Use callbacks to share common setup or constraints between actions.
      def set_booking
        @booking = Booking.find(params[:id])
      end

      def set_hotel
        @hotel = Hotel.find(params[:hotel_id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.

      def booking_params
        if ['index', 'destroy'].include?(params[:action])
          params.permit(:booking)
        else
          params.require(:booking).permit(:date_in, :date_out, :hotel_id,:user_id,:status)
        end

      end

    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  before_action :set_hotel, only: [:new,:create]
  before_action :authenticate_user!

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.where(user_id: current_user.id)
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = current_user.bookings.new(booking_params)
    @booking.hotel = @hotel
    respond_to do |format|
      if @booking.save
        format.html { redirect_to booking_path(@booking), notice: 'La reserva ha sido creada satisfactoriamente.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to booking_path(@booking), notice: 'La reserva ha sido actualizada con exito satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_path, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    def set_hotel
      @hotel = Hotel.find(params[:hotel_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:date_in, :date_out, :hotel_id)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_for([@hotel,@booking]) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
  <div class="row">

    <div class="input-field">
      <i class='material-icons prefix green-text'>today</i>
      <%= f.label 'Fecha de ingreso', class: 'datepicker' %>
      <%= f.text_field :date_in, class: 'datepicker' %>
    </div>

    <div class="input-field">
      <i class='material-icons prefix red-text'>today</i>
      <%= f.label 'Fecha de salida',class: 'datepicker' %>
      <%= f.text_field :date_out , class: 'datepicker' %>
    </div>

    <br>
    <div class="actions">
      <%= f.submit 'Guardar', class: 'btn waves-effect waves-light blue darken-4' %>
    </div>
  </div>
</div>
    
<% end %>
<script>
  $('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    selectYears: 15 // Creates a dropdown of 15 years to control year
  });
</script>

app/views/bookings/edit.html.erb
<h1 class="center blue-text">Editar Reserva</h1>
<%= render 'form' %>
<div class="container">
  <div class="row">
    <div class="col s12">


  <%= link_to 'Atras', bookings_path%>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container">
  <div class="row">
    <div class="col s12">

      <h1>Lista de reservas</h1>
      <table class="responsive-table highlight">
        <thead>
          <tr>
            <th>Estado</th>
            <th><i class="material-icons blue-text left">date_range</i>Fecha de ingreso</th>
            <th><i class="material-icons blue-text left">today</i>Fecha de salida</th>
            <th><i class="material-icons blue-text left">hotel</i>Hotel</th>
          </tr>
        </thead>
        <tbody>
          <% @bookings.each do |booking| %>
          <tr>
            <td><%= booking.estado %></td>
            <td><%= booking.date_in %></td>
            <td><%= booking.date_out %></td>
            <td><%= booking.hotel.name %></td>
            <td><%= link_to 'Mas informacion', booking %></td>
            <td><%= link_to 'Editar', edit_booking_path(booking) %></td>
            <td><%= link_to 'Eliminar', booking, method: :delete, data: { confirm: 'Estas seguro que deseas eliminar esta reserva?' } %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <br>
      <p class="green-text">&iquest;Aun no tienes una reserva? &iquest;Que esperas? &iexcl;Obten una reserva en uno de los mejores hoteles internacionales!</p>
      <%= link_to 'Crear nueva reserva', hotels_path, class: 'waves-effect waves-light btn blue' %>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<h1 class="center blue-text">Crear Reserva</h1>
<%= render 'form' %>
<br>
<div class="container">
  <%= link_to 'Back', root_path %>
</div>

app/views/bookings/show.html.erb
<div class="Container center">
 <div class="row">

   <ul class="collection with-header">
     <li class="collection-header">
       <h4>Informacion de la reserva</h4>
     </li>
     <li class="collection-item">Estado de la reserva: <%=@booking.estado %></li>
     <li class="collection-item">Fecha de ingreso: <%= @booking.date_in %></li>
     <li class="collection-item">Fecha de salida: <%= @booking.date_out %></li>
     <li class="collection-item">Hotel de la reserva: <%= @booking.hotel.name %></li>
   </ul>

<%= link_to 'Editar', edit_booking_path(@booking) %> |
<%= link_to 'Atras', root_path %></div>


</div>