config/routes.rb
Rails.application.routes.draw do

  resources :hotels do
    resources :bookings
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",:registrations => "registrations",:sessions => "sessions"}

  resources :users do
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :hotels
      resources :bookings
    end
  end

  resources :bookings
  root 'welcome#index'

end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
	has_many :bookings,inverse_of: :hotel
  accepts_nested_attributes_for :bookings
  validates_presence_of :name

  def self.search(search)
    if search
      # find(:all,:conditions => ['name LIKE ?', "%#{search}%"])
      @q = "%#{search}%"
      where("name ILIKE ?",@q)
    else
      find(:all)
    end
  end
end

app/controllers/api/v1/hotels_controller.rb
module Api
  module V1
    class HotelsController < ApplicationController
      # acts_as_token_authentication_handler_for User
      respond_to :json

      def index
        custom_header_value = request.headers['x-name']
        @hotels = Hotel.search(custom_header_value)
        respond_with hotels: @hotels
      end

      def show
        respond_with Hotel.find(params[:id])
      end

      def create
        respond_with Hotel.create(params[:hotel])
      end

      def update
        respond_with Hotel.update(params[:id],params[:hotel])
      end

      def destroy
        respond_with Hotel.destroy(params[:id])
      end


    end
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: [:show]

  # GET /hotels
  # GET /hotels.json
  def index
    if params[:search].nil?
    @hotels = Hotel.all
    else
      @hotels = Hotel.search(params[:search])
    end
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'El hotel ha sido creado con exito.' }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1
  # PATCH/PUT /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to @hotel, notice: 'El hotel ha sido actualizado con exito.' }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to hotels_url, notice: 'El hotel ha sido eliminado.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_hotel
    @hotel = Hotel.find(params[:id])
  end


  # Never trust parameters from the scary internet, only allow the white list through.
  def hotel_params
    #params.require(:hotel).permit(:name, :email, :phone, :about, :stars, :address, :photo_url,reserves_attributes: [:status,:date_in,:date_out,:id])
    params.require(:hotel).permit(:name, :email, :phone, :about, :stars, :address, :photo_url)
  end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_form.html.erb
<%= form_for(@hotel) do |f| %>
<% if @hotel.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>
  <ul>
    <% @hotel.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="container">
  <div class="row">
    <div class="input-field col s12">
      <i class='material-icons prefix blue-text'>face</i>
      <%= f.label 'Nombre' %>
      <%= f.text_field :name, class: "validate" %>
    </div>
    <div class="input-field col s12">
      <i class='material-icons prefix blue-text'>email</i>
      <%= f.label :email %>
      <%= f.email_field :email, class: "validate" %>
    </div>
    <div class="input-field col s12">
      <i class='material-icons prefix blue-text'>call</i>
      <%= f.label 'telefono' %>
      <%= f.telephone_field :phone, class: "validate" %>
    </div>
    <div class="input-field col s12">
      <i class='material-icons prefix blue-text'>comment</i>
      <%= f.label :acerca %><
      <%= f.text_area :about, class: "materialize-textarea validate" %>
    </div>
    <div class="input-field col s12">
      <i class='material-icons prefix yellow-text'>star rate</i>
      <%= f.label :estrellas %>
      <%= f.number_field :stars, class: "validate" %>
    </div>
    <div class="input-field col s12">
      <i class='material-icons prefix blue-text'>add_location</i>
      <%= f.label :direccion %>
      <%= f.text_field :address, class: "validate" %>
    </div>
    <div class="input-field col s12">
      <i class='material-icons prefix blue-text'>add_a_photo</i>
      <%= f.label :photo_url %>
      <%= f.text_field :photo_url %>
    </div>
    <br>
    <div class="actions">
      <%= f.submit 'Guardar', class: 'btn waves-effect waves-light blue darken-4' %>
    </div>
  </div>
</div>
<% end %>

app/views/hotels/edit.html.erb
<h1 class="center">Editar Hotel</h1>
<%= render 'form' %>
<div class="container">
	<div class="row">
		<div class="col s12">
			<%= link_to 'Atras', hotels_path %>
		</div>
	</div>
</div>

app/views/hotels/index.html.erb
<p id="notice"><%= notice %></p>
<h4 class="center blue-text">&iexcl;Estos son los hoteles que tenemos para ti!</h4>
<div class="container">
  <div class="center">
    <%= form_tag hotels_path, method: 'get' do %>
        <%= text_field_tag :search, params[:search],placeholder: '¡Ingresa el nombre del hotel que buscas!',maxlength: 25 %>
        <%= submit_tag('Buscar',name: nil,class: "btn waves-effect waves-light blue darken-4") %>
    <% end %>
  </div>
</div>
<div class="container">
  <div class="row">
    <% @hotels.each do |hotel| %>
    <div class="col s12 m6 l6">
      <div class="card medium hoverable">
        <div class="card-image">
          <%= image_tag("milano.jpg",class:"shrinkToFit",size:"226") %>
          <span class="card-title"> <%= hotel.name %> </span>
        </div>
        <div class="card-content">
          <p> <%= hotel.about %> </p>
        </div>
        <div class="card-action">
          <%= link_to 'Mas informacion', hotel %>
          <% unless current_user.nil? %>
              <% if current_user.admin? %>
                  <%= link_to 'Editar', edit_hotel_path(hotel) %>
                  <%= link_to 'Eliminar', hotel, method: :delete, data: { confirm: 'Estas seguro que deseas eliminar este hotel?' } %>
              <% end %>
          <% end%>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
<% unless current_user.nil? %>
  <% if current_user.admin? %>
  <div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
    <!-- Hay que utilizar comillas simples en caso de que se quiera utilizar una clase dentro del link_to -->
    <%= link_to "<i class='large material-icons'>note_add</i>".html_safe, new_hotel_path, :class => "btn-floating btn-large blue darken-4" %>
  </div>
  <% end %>
<% end %>

app/views/hotels/new.html.erb
<h4 class="center blue-text">Crear hotel</h4>
<%= render 'form' %>
<div class="container">
<%= link_to 'Atras', hotels_path %>
</div>

app/views/hotels/show.html.erb
<h3 class="center">Informacion</h3>
<div class="container center">
  <div class="row">
    <ul class="collection with-header">
      <li class="collection-header">
        Nombre del hotel: <%=@hotel.name %>
      </li>
      <li class="collection-item">Email de contacto: <%= @hotel.email %></li>
      <li class="collection-item">Telefono de contacto: <%= @hotel.phone %></li>
      <li class="collection-item">Acerca: <%= @hotel.about %></li>
      <li class="collection-item">Estrellas <br>
      <% c = 0
      until c == @hotel.stars
        c += 1
      %>
        <i class="small material-icons yellow">star</i>
          <%end%>
      </li>
      <li class="collection-item">Direccion: <%= @hotel.address %></li>
      <li class="collection-item">Fotos: <%= @hotel.photo_url %></li>
    </ul>

  </div>
  <% if current_user.try(:admin?) %>
  <%= link_to 'Editar', edit_hotel_path(@hotel) %> |
  <%end %>
  <%= link_to 'Atras', hotels_path %> |
  <%= link_to 'Reservar!', new_hotel_booking_path(@hotel)%>

</div>