config/routes.rb
Rails.application.routes.draw do

  resources :hotels do
    resources :bookings
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",:registrations => "registrations",:sessions => "sessions"}

  resources :users do
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :hotels
      resources :bookings
    end
  end

  resources :bookings
  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Pirala</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
		<%= csrf_meta_tags %>
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	</head>
	<body>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<!-- Navbar -->
		<header>
			<nav>
				<div class="blue nav-wrapper">
					<a href="#" class="brand-logo center">Pirala!</a>
          <%= link_to '<i class="material-icons">menu</i>'.html_safe, "#", :"data-activates" => "mobile-demo", class: "button-collapse right"%>
					<%= link_to "Pirala!", root_path ,class: "brand-logo center" %>
					<ul id="nav-mobile" class="right hide-on-med-and-down">
						<li>
              <%= link_to "Hoteles",hotels_path,class: "left" %>
							<% if user_signed_in? %>
							<%= link_to "Reservas",bookings_path, class: "left" %>
							<!-- codigo para los link con materialicon -->
							<%= link_to "<ul class='right hide-on-med-and-down'>
								<li>
									<i class='material-icons left'>perm_identity</i>#{current_user.name}
								</li>
							</ul>".html_safe,"/users/edit",class: "center" %>
							<!-- fin del codigo para link con materialicon -->
							<%=link_to "Cerrar sesion","/users/sign_out",class: "right", method: :delete%>
							<% else %>
							<!-- <p class="large material-icons left">perm_identity</p> -->
							<%= link_to "Iniciar sesion","/users/sign_in" %>
							<% end %>
						</li>
					</ul>

          <!--Inicio del navbar-collapsable para mobiles-->
          <ul class="side-nav blue" id="mobile-demo">
            <% if user_signed_in? %>
                <li>
                  <i class='small material-icons left'>perm_identity</i>
                  <%= link_to "#{current_user.name}","/users/edit",class: "white-text" %>
                </li>
                <li>
                  <i class='small material-icons left'>hotel</i>
                  <%= link_to "Hoteles",hotels_path,class: "white-text" %>
                </li>
                <li>
                  <i class='small material-icons left'>today</i>
                  <%= link_to 'Reservas', bookings_path , class: 'white-text' %>
                </li>
                <li>
                  <i class='small material-icons left'>exit_to_app</i>
                  <%=link_to 'Cerrar sesion', '/users/sign_out', class: 'white-text', method: :delete%>
                </li>
            <%else %>

                <li>
                  <i class='small material-icons left'>account_box</i>
              <%= link_to 'Iniciar Sesion', '/users/sign_in', class: 'white-text' %>
            </li>
                <li>
                  <i class='small material-icons left'>hotel</i>
                  <%= link_to "Hoteles",hotels_path,class: "white-text" %>
                </li>
            <%end%>
          </ul>

          <!--Final del navbar mobile-->
				</div>
			</nav>
		</header>
		
		<!-- Mostrar los notices como Toast -->
		<% if notice != nil %>
				<script type="text/javascript">
				Materialize.toast('<%= notice %>', 4000)
				</script>
		<%end%>

		<% if alert != nil %>
			<script type="text/javascript">
				Materialize.toast('<%= alert %>', 4000)
				</script>
		<% end %>
		

		<!-- final navbar -->
		<main>
		<%= yield %>
		</main>
		<footer class="blue page-footer">
			<div class="footer-copyright">
				<div class="container">
					<p class="white-text center ">Pirala 2016 Todos los derechos reservados</p>
				</div>
			</div>
		</footer>
	</body>
</html>